### ISSUE TITLE
Urgent! Snakemake/oncopipe compatibility

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#87]
I desperately need the latest Snakemake version 5.23 because it solves a scheduler bug that prevents me from limiting the number of enormous temp files my pipeline creates (see [here](https://github.com/snakemake/snakemake/issues/251) for a description). However it seems I can't have both oncopipe 1.0.10 and Snakemake 5.23 in the same env - if I install oncopipe after Snakemake 5.23 it downgrades Snakemake to 5.18. Is there a reason for this limitation? Is it easy to fix?

**Comment by BrunoGrandePhD** [comment]
Thanks for the heads-up! Snakemake 5.19 caused issues (see #43), so I constrained the Snakemake version. I can allow higher versions of Snakemake if we can confirm that there are no `ChildIOException` errors that come up.

**Comment by lkhilton** [comment]
I thought I remembered a conversation about constraining Snakemake versions but I couldn't find it. 

As of right now any Snakemake > 5.20 hangs indefinitely at `Building DAG of jobs`. Not looking good. I don't know if this is a bug, oncopipe compatibility, something about the way the LCR modules are set up...?

**Comment by BrunoGrandePhD** [comment]
@rdmorin described a similar issue a few weeks ago that ended up being related to the file system. Can you confirm that switching back to version 5.18 rescues the phenotype (for lack for a better term)?

**Comment by lkhilton** [comment]
Can confirm. Here's what I did: 

1. Created a new `snakemake-test` conda environment with `snakemake-minimal=5.19.0`. Installed `oncopipe-1.0.10` with `pip install --no-dependencies -e /path/to/lcr-modules/oncopipe`. Manually installed Pandas with `pip install pandas`. 
2. Performed a dry run on four tumour samples input to my GRIDSS pipeline. This threw the `ChildIO` exception as expected for Snakemake 5.19. 
3. Updated snakemake with `conda install snakemake-minimal=5.20`. Dry run hangs indefinitely at `Building DAG of jobs...`. 
4. Deactivated `snakemake-test` env to `gambl-default` env, which includes `oncopipe-1.0.9` and `snakemake-minimal=5.14.0`. Dry run completes in < 5 seconds.

**Comment by lkhilton** [comment]
I was suspicious that this had something to do with changing Snakemake versions and trying to run it on a directory that had partial outputs from a prior run. Indeed if I upgrade to `snakemake-minimal=5.23` and direct the output to a fresh results directory, I can get it past the `Building DAG of jobs...` stage, but the `ChildIOException` error persists: 
```
Building DAG of jobs...
Executing subworkflow reference_files.
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
('/projects/rmorin_scratch/lcr-modules-references-DEV/genomes/grch37/downloads/encode_blacklist/blacklist.encode.grch37.bed', hardlink_download)
('/projects/rmorin_scratch/lcr-modules-references-DEV/genomes/grch37/downloads/encode_blacklist/blacklist.encode.grch37.bed', get_blacklist_download)
```

Is the reference workflow actually supposed to write to the same output file at two different steps? Or is this a problem with the newer DAG calculation methods?


Also, this is in a rule I wrote...

**Comment by BrunoGrandePhD** [comment]
The `ChildIOException` errors might be legitimate and the result of stricter DAG validation. What would be useful is a minimal reproducible example for triggering a `ChildIOException`. Does one come up if you run the demo project on the latest `master` with perhaps only one of the more established modules enabled (_e.g._ `manta` or `star`)?

**Comment by Kdreval** [comment]
I was running the demo project about a week ago testing the star module. Also, run the demo project this weekend on the branch `demo_repairs`. I did not come up with `ChildIOException` error. I am using the snakemake version provided by oncopipe and I believe it is `5.18.1`.

**Comment by lkhilton** [comment]
I'm almost sure it's a problem related to the way I'm downloading the Encode Blacklist in the reference files workflow. To test that assumption I'm removing the steps related to those reference files and will test it again and report back. At some point in the future I'll probably ask you to take a look at the broken rules to see if you can help me fix them.

**Comment by BrunoGrandePhD** [comment]
I'll gladly help you resolve the problematic rules if there are any! Thanks for doing the legwork of further isolating the issue. Much appreciated!

**Comment by lkhilton** [comment]
I deleted all the additional rules in the reference workflow and reverted to version 2.3 of the workflow, so I've eliminated any problems related to the subworkflow. I'm narrowing down the reason behind Snakemake hanging at the `Building DAG of jobs...` step, even on a dry run. 

Running Snakemake 5.23 and oncopipe 1.0.10. 

When I set the output directory to `results/` or `results/{unix_group}/`, Snakemake 5.23 hangs indefinitely while building the DAG. Note that `results/` is a symlink to `/projects/nhl_meta_analysis_scratch/results_local`.  I created a directory in my own `gambl` repo at `/projects/rmorin/projects/gambl-repos/gambl-lhilton/results_test` (NOT a symlink) and the dry run completes in seconds.

**Comment by lkhilton** [comment]
Can also confirm that this behaviour is resolved in Snakemake 5.14.

**Comment by BrunoGrandePhD** [comment]
What if the symlink in your repo points to an empty directory in `nhl_meta_analysis_scratch`? I just want to determine if it's related to the symlink or whether the output directory is prepopulated.

**Comment by lkhilton** [comment]
Good suggestion, I tried that. It created the sub-directories within, e.g. `gambl/tool-name-version/00-inputs`, but still hangs indefinitely after that.

**Comment by lkhilton** [comment]
I'm suspicious this is related to the ChildIO exception and how Snakemake has been [checking output files](https://github.com/snakemake/snakemake/issues/413) since 5.19.

**Comment by BrunoGrandePhD** [comment]
Can you confirm that the issue is absent with Snakemake 5.18.1 and present with Snakemake 5.19.0? The number of [changes](https://github.com/snakemake/snakemake/compare/v5.18.1...v5.19.0) in Python files between these two version is finite, so we could try to specifically identify the change that introduced the regression.

**Comment by lkhilton** [comment]
Can confirm it works seamlessly in 5.18.1. 

In 5.19.0 and 5.19.1 the DAG doesn't hang indefinitely, but I get this error: 
```
ChildIOException:
File/directory is a child to another output:
('/projects/analysis33/E00944/merge53948_bwa-mem-0.7.6a-sb/150bp/hg19a/E00944_2_lanes_dupsFlagged.bam', _gridss_input_bam)
('/projects/analysis33/E00944/merge53948_bwa-mem-0.7.6a-sb/150bp/hg19a/E00944_2_lanes_dupsFlagged.bam', _hmftools_input_bam)
```

This demonstrates how the bug in 5.19 manifests - the same file is symlinked to `00-inputs` within two different modules, which Snakemake 5.19 is interpreting as the same output file. 

From 5.20 and up, Snakemake hangs indefinitely at `Building DAG of jobs...`.

**Comment by BrunoGrandePhD** [comment]
Thanks for confirming that. The following commit on the snakemake repo occurred between versions 5.18.1 and 5.19.0, and it involves raising `ChildIOException` errors. I suspect this has to do with the new `ChildIOException` errors we started seeing. I'm going to try to understand what's going on in that commit tonight. 

https://github.com/snakemake/snakemake/commit/0c289a650803f08f35e68392fb066e8977950b2b

**Comment by lkhilton** [comment]
I found it tricky to trace the origin of the bug, but FYI folks are reporting that the code in this [PR](https://github.com/snakemake/snakemake/pull/447) is fixing the ChildIOException.

**Comment by BrunoGrandePhD** [comment]
Would it be useful if I generated a version of Snakemake that applies that PR on the latest stable version?

**Comment by lkhilton** [comment]
Ooh, yes that would be extremely useful

**Comment by rdmorin** [comment]
This request isn't as urgent as it once was though, right Laura? Because the grouping of rules solved your immediate issue.

**Comment by lkhilton** [comment]
I tried out the patch, it did not fix the indefinite hanging problem.

**Comment by lkhilton** [comment]
I made a minimal example that can reproduce the ChildIO exception error, but I can't reproduce the indefinite hanging at the DAG building stage behaviour. This leads me back to the possibility that somehow Snakemake is getting stuck after `op.setup_module` runs, but I can't fathom why it's failing in the context of `lcr-modules` only when the results directory is a symlink. I will explore this bug further. 

My reprex is in `/home/lhilton/repos/snakemake-test` if you are interested in exploring further, Bruno. But Ryan is right, I have a temporary (sub-optimal) fix for now, so this is no longer "Urgent!"

**Comment by BrunoGrandePhD** [comment]
I have merged the PR's edits into version 5.23.0 of Snakemake. The merge was successful without any conflicts. You can install my "fixed" version of v5.23.0 by running the following `pip` command in your conda environment. 

```
pip install git+https://github.com/BrunoGrandePhD/snakemake.git@5.23.0-fixed
```

Let me know if this fixed version leads to any change in behaviour with respect to DAG building stage.

**Comment by rdmorin** [comment]
Does anyone know if this resolved the issue @lkhilton was having?

**Comment by BrunoGrandePhD** [comment]
As an FYI, there's mention of an option to group jobs in the latest version of Snakemake to improve performance. I don't know if this will help with running jobs for GAMBL. 

https://github.com/snakemake/snakemake/blob/master/CHANGELOG.rst

**Comment by lkhilton** [comment]
I did try out the patch (as I said above it didn't fix the indefinite hanging problem). Ryan discovered the job grouping and I've been using that as a fix for now, but the DAG of my pipeline means that I have to run the default normal through alone first, or else it tries to group all the unpaired tumours with the default unmatched normal in one giant group. I haven't had time yet to explore the specific changes that are causing Snakemake to hang at the DAG-building stage.

**Comment by lkhilton** [comment]
I've done some debugging/digging and I think we can close this. 

1. Snakemake 5.25 fixes the problem where Snakemake interpreted symlinks as outputs written to the same file.
2. The problem where the DAG solving step persists in 5.25. This problem is mentioned [here](https://github.com/snakemake/snakemake/issues/568). It seems the source of the problem is known but no fixes are in the works yet. I'm keeping an eye on it, if they solve this problem in the future I'll let @BrunoGrandePhD know that we can change the oncopipe requirements, but for now the current restriction needs to stand. 

Also, I did manage to test Snakemake priorities and the new ILP scheduler in 5.25, and it did NOT improve the mess that was GRIDSS job scheduling, which was disappointing. I worked out a way to force the default unmatched normals to be run first, then I group the tumour-only or matched tumour/normal jobs.

**Comment by BrunoGrandePhD** [comment]
When you have a moment, you can try this branch on my repo. I basically merged the changes from `v5.25.0` into my previous `v5.23.0-fixed` branch, and I tried disabling the file inventory line that's referenced in the issue you linked to. I have no idea if this will break anything, but it might help with the stalling you've experienced. 

```
pip install git+https://github.com/BrunoGrandePhD/snakemake.git@5.25.0-fixed
```
